[package]
name = "phoible-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.11"
clap_derive = "4.1.9"
csv = "1.2.1"
logos = "0.12.1"
